name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Build and Start
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./antd-pro
          build: yarn build
          start: yarn start
          
#       - name: Database Testing
#         uses: cypress-io/github-action@v2
#         with:
#           working-directory: ./EFormApi
#           run: dotnet run
      
#       - name: Automate Testing
#         uses: cypress-io/github-action@v2
#         with:
#           working-directory: ./antd-pro
#           start: yarn start
#         env:
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           DEBUG: "@cypress/github-action"
